### ISSUE TITLE
extras-plaintasks nothing happens

### ISSUE THREAD

**Issue by JimAmuro** [equinusocio/material-theme#1013]
### Summary

When I hit extras-plaintasks, nothing happens, and there is an error log in ST console.
...
### Expected behavior

Maybe show list of color schemes for PlainTasks?
...
### Actual behavior

Nothing happens. Shows error log. 

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "utils.extras in C:\Users\Hui Sun\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 170, in run
  File "utils.extras in C:\Users\Hui Sun\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 147, in display_list
  File "utils.extras in C:\Users\Hui Sun\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 56, in get_theme
  File "utils.extras in C:\Users\Hui Sun\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 48, in get_settings
KeyError: 'PlainNotes'
```

...
### Steps to reproduce

hit extras-plaintasks
### Environment
- Operating system and version:
  - Windows 10
- Sublime Text:
  - Build 3126
- Material Theme release:
  - v4

**Comment by equinusocio** [comment]
You should firs create a new task document. And the run Extras: PlainTasks, check this gif:

![2016-10-30 20 18 10](https://cloud.githubusercontent.com/assets/10454741/19839231/434f1d04-9ede-11e6-87a8-23033a42ddc1.gif)

**Comment by JimAmuro** [comment]
@equinusocio Cool! I did the same thing but nothing happens... From the error log I think it is the problem with the `extras.py` file.

**Comment by equinusocio** [comment]
Try to run Package Control: Satisfy dependencies

**Comment by JimAmuro** [comment]
@equinusocio 
```
Package Control: All dependencies have been satisfied
```

**Comment by equinusocio** [comment]
@oivva You have te same issue with Boxy?

**Comment by oivva** [comment]
@equinusocio I'll investigate this, I think I forgot about checking if `PlainNotes` is installed.

**Comment by oivva** [comment]
@JimAmuro Try to restart Sublime Text. Do you see the same error?

**Comment by oivva** [comment]
@equinusocio I've recently checked it, works like a charm. I think the problem is related to another plugin.

**Comment by JimAmuro** [comment]
@equinusocio I solved this by update `extras.py` to https://github.com/equinusocio/material-theme/commit/4e3d7d9e2c3a1021b7678d6928e714628141e3fd.

**Comment by equinusocio** [comment]
Right, 4e3d7d9e2c3a1021b7678d6928e714628141e3fd
