### ISSUE TITLE
word matching highlighter   [QUESTION]

### ISSUE THREAD

**Issue by lanox** [equinusocio/material-theme#1103]
Love the theme.

I have a question is it possible to change the way recurrence of word is highlighted.
in screen shoot below you can see that word name is highlighted with grey light color but other have yellow border around it. Is it possible to make them all light grey ? 
![screen shot 2017-03-06 at 2 31 32 pm](https://cloud.githubusercontent.com/assets/7599183/23595893/9e5c93bc-0279-11e7-882a-ec7bf82263e3.png)

thanks

**Comment by equinusocio** [comment]
Mmmm i really don't know. At the moment i can't test this, you should try to extract and edit this file `/schemes/Material-Theme-Darker.tmTheme` and change:

```xml
<key>findHighlight</key>
<string>#F8E71C</string>
```

**Comment by ymjdev** [comment]
com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found
java.lang.NoSuchMethodError: com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found
	at com.chrisrm.idea.MTTabsPainterPatcher$MTTabsPainter.<init>(MTTabsPainterPatcher.java:106)
	at com.chrisrm.idea.MTTabsPainterPatcher.patchPainter(MTTabsPainterPatcher.java:73)
	at com.chrisrm.idea.MTTabsPainterPatcher.access$000(MTTabsPainterPatcher.java:29)
	at com.chrisrm.idea.MTTabsPainterPatcher$1.selectionChanged(MTTabsPainterPatcher.java:57)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy79.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:1548)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1031)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:655)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.h(FocusManagerImpl.java:639)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:609)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:61)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:107)
	at com.intellij.openapi.util.EdtRunnable.lambda$run$0(EdtRunnable.java:27)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2621)
	at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lanox** [comment]
@equinusocio how do you know? I googled but not much as come up.?

**Comment by equinusocio** [comment]
Sublime Text 3 is in beta from 3 years, so the official version is the Sublime Text 2. The latest ST 3 beta update was released on 23 September 2016, and the latest ST 3 Dev Channel release was released also on 23 September 2016. Six months without updates, hundreds of issues, no "Update" from the team...  it seem all but not an active project.

**Comment by tazV2** [comment]
stay positive Sir! 
I have to because I spent $70 recently :( 
https://forum.sublimetext.com/t/st3-plans-what-happened-to-all-the-activity-last-year/26526

**Comment by equinusocio** [comment]
The "management" ST is a mess of topics, discussions scattered around, missed documentations... now i'm using VSC and i can see a public roadmap and the development status
