### ISSUE TITLE
ImportError: No module named 'yaml' - Not Able to Activate Material Theme 

### ISSUE THREAD

**Issue by swaroophumane** [equinusocio/material-theme#1229]
![sublime text](https://user-images.githubusercontent.com/36727484/37339934-56e73918-26e2-11e8-8ede-5202244d886f.png)
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

Not able to use Material Theme.

ignored packages updated to: ["Material Theme", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MT in C:\Users\Dipankar\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 1, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils in C:\Users\Dipankar\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 3, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils.config in C:\Users\Dipankar\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 8, in <module>
  File "C:\Users\Dipankar\AppData\Roaming\Sublime Text 3\Packages\mdpopups\st3\mdpopups\__init__.py", line 27, in <module>
    from . import frontmatter
  File "C:\Users\Dipankar\AppData\Roaming\Sublime Text 3\Packages\mdpopups\st3\mdpopups\frontmatter.py", line 2, in <module>
    import yaml
ImportError: No module named 'yaml'

...

### Expected behavior

I should get "Material Theme : Activate Configuration"

### Actual behavior
Only getting "Material Theme : Advance Configuration".
...

### Steps to reproduce
1. Fresh installation of Sublime Text 3.
2. Install Material Theme
3. (No Activation prompt)
### Environment

* Operating system and version:
  *Windows 10
* Sublime Text:
  * Build 3143 64bit
* Material Theme release:
  * v4.1.4

**Comment by phaibin** [comment]
same problem

**Comment by equinusocio** [comment]
@zpreston123

**Comment by zpreston123** [comment]
@equinusocio Sure, this should be an easy fix.  It looks like a dependency issue related to mdpopups.  The latest version requires pyyaml and pymdownx, which are missing in the dependencies file.  Similar issue happens in Boxy Theme after installation:  https://github.com/ihodev/sublime-boxy/issues/201.

**Comment by zpreston123** [comment]
@swaroophumane @phaibin Just pushed a new release that should fix this issue.  Hope it helps =)
