### ISSUE TITLE
Material Theme Config option disabled, missing "pygments"

### ISSUE THREAD

**Issue by Hemerythrin** [equinusocio/material-theme#931]
Sublime text version 3114 windows x64
Neither running "Satisfy Dependencies" multiple times nor reinstalling the plugin have helped.

Relevant console output:
```
reloading plugin Material Theme.material_theme
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "material_theme in C:\Users\mjkam\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 5, in <module>
  File "C:\Users\mjkam\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\__init__.py", line 19, in <module>
    from .st_scheme_template import Scheme2CSS, POPUP, PHANTOM
  File "C:\Users\mjkam\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\st_scheme_template.py", line 22, in <module>
    from pygments.formatters import HtmlFormatter
ImportError: No module named 'pygments'
reloading plugin Material Theme.urls
```

**Comment by equinusocio** [comment]
Related to #925

**Comment by bagelbits** [comment]
I'm also seeing the same error. In addition, farther down in the console, I see this error as well:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "material_theme in /Users/zardoz/Library/Application Support/Sublime Text 3/Installed Packages/Material Theme.sublime-package", line 5, in <module>
  File "/Users/zardoz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 16, in <module>
    from . import version as ver
ImportError: cannot import name version
```

Mac OSX 10.11.6
ST Build 3114
Material Theme 3.1.3

**Comment by bagelbits** [comment]
There appears to be an issue between having both Material Theme and BracketHighlighter for me.

The traceback I'm seeing similar to @Hemerythrin looks like this:
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "changes in /Users/zardoz/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 4, in <module>
  File "/Users/zardoz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 19, in <module>
    from .st_scheme_template import Scheme2CSS, POPUP, PHANTOM
  File "/Users/zardoz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 22, in <module>
    from pygments.formatters import HtmlFormatter
ImportError: No module named 'pygments'

**Comment by luannguyenQV** [comment]
I am also, Sublime crash & I can't use Material Theme, It's move to backup. I try re-install many time but impossible.

**Comment by equinusocio** [comment]
@luannguyenQV provide your sublime text info please. @bagelbits Try to upgrade BracketHighlighter to 2.21.3 (released yesterday)

**Comment by mcfattydk** [comment]
@equinusocio I also has this problem - I just don't get any error in my console, but my "Material Theme Config" is disabled.

**Comment by equinusocio** [comment]
3.1.4 released with the pygments dependencies. This should fix this error dependencies. 

@mcfattydk Please run `Satisify Dependencies` and restart sublime text. Also retry in 1 hr and you will get the new 3.1.4 release that should fix this. After updating to 3.1.4, run again `Satisfy Dependencies` and if the issue persist paste here the info that you'll get from `Theme Info` command, inside the Material Theme context menu.

**Comment by equinusocio** [comment]
Someone with ST 3114+ can check the latest 3.1.4 release?

**Comment by BlueHaunter** [comment]
Package Control isn't finding the latest upgrade yet.

**Comment by mcfattydk** [comment]
@equinusocio Okay, I'll try that then - but like @BlueHaunter, I'm not seeing any 3.1.4 yet.

**Comment by equinusocio** [comment]
@BlueHaunter will be available in minutes. PC update packages after 1 hr, you can check the update status here https://packagecontrol.io/packages/Material%20Theme

**Comment by equinusocio** [comment]
with the 3.1.4 you will have a new `Theme Info` under the `Material Theme` menu. Run `Satisfy Dependencies` and the run `Theme Info`. Paste here the result.

**Comment by BlueHaunter** [comment]
```
• ST ver.:   3119
• Platform:   linux
• Arch:   x64
• Theme:   3.1.4
• Install via PC:   True
• mdpopups:   1.9.1
• markdown:   2.6.6
• pygments:   2.1a0
• jinja2:   2.8
```

**Comment by BlueHaunter** [comment]
It's working now. Thanks :)

**Comment by equinusocio** [comment]
I wait for a @mcfattydk feedback then i will close. I hope.

**Comment by mcfattydk** [comment]
• ST ver.:   3114
• Platform:   osx
• Arch:   x64
• Theme:   3.1.4
• Install via PC:   False
• mdpopups:   1.9.1
• markdown:   2.6.6
• pygments:   2.1a0
• jinja2:   2.8

**Comment by mcfattydk** [comment]
It also working for me now!
Thank you, @equinusocio!
