### ISSUE TITLE
Build errors on Win 10

### ISSUE THREAD

**Issue by jrappen** [equinusocio/material-theme#959]
### Summary

```text
λ gulp

...

[xx:xx:xx] Starting 'build'...

...

[xx:xx:xx] Starting 'build:widget-themes'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
 ReferenceError: comment is not defined
    at eval (lodash.templateSources[4]:11:11)
    at DestroyableTransform._transform (~\AppData\Desktop\Material Theme\node_modules\gulp-template\index.js:21:40)
    at DestroyableTransform.Transform._read (~\AppData\Desktop\Material Theme\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (~\AppData\Desktop\Material Theme\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (~\AppData\Desktop\Material Theme\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (~\AppData\Desktop\Material Theme\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (~\AppData\Desktop\Material Theme\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at DestroyableTransform.ondata (~\AppData\Desktop\Material Theme\node_modules\readable-stream\lib\_stream_readable.js:531:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
```

### Expected behavior

1. gulp should find the `subl` cmd
2. gulp (the default build) should work

### Actual behavior

1. `work-around`: had to put the subl exe path into `gulpfile.js`
2. haven't found a resolution

### Steps to reproduce

Run:

* `npm install`
* `gulp`

### Environment

* Win 10 Pro x64
* cmder
  * node
    * windows-build-tools (with python 2.7)
    * npm
    * gulp
  * ST3 `Build 3120` x64 (zip)
    * PackageDev `v2.1.0`
    * Material Theme `v3.1.9`

**Comment by equinusocio** [comment]
I have no problem on OS X and a Win10 virtual machine. The command already exist inside the gulp file, at line 265.

```
.pipe($.exec('subl "<%= file.path %>" && subl --command "convert_file" && subl --command "hide_panel"'))
```

**Comment by jrappen** [comment]
* The path is fine I guess. That problem is probably related to cmder (@cmderdev) not letting gulp access the `subl` command, which works perfectly fine when using it directly in cmder.
* I still get that error when building widget-themes, but maybe a typo on my part in an edit. Will close issue for now and re-open if problem persists.
