### ISSUE TITLE
Installing the theme makes Schemr stop work

### ISSUE THREAD

**Issue by fcaldera** [equinusocio/material-theme#966]
### Summary
I don't know if I should report this to you guys but this theme makes Schemr stop work.
https://packagecontrol.io/packages/Schemr

### Expected behavior
Schemr should list all the installed color schemes.

### Actual behavior
Nothing is displayed. An error appears in the console.

### Steps to reproduce

1. cmd + shift + p
2. Look for `schemr: list all schemes`
3. See the sublime console

```shell
Error parsing Packages/Material Theme/schemes/OLD/Material-Theme.tmTheme
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "schemr in /Users/fcaldera/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 247, in run
  File "schemr in /Users/fcaldera/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 99, in list_schemes
  File "schemr in /Users/fcaldera/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 207, in parse_scheme
  File "schemr in /Users/fcaldera/Library/Application Support/Sublime Text 3/Installed Packages/Schemr.sublime-package", line 207, in <listcomp>
ValueError: invalid literal for int() with base 16: '<%'
```

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3114
* Material Theme release:
  * v3.1.10

**Comment by benweier** [comment]
Hi @fcaldera I've just fixed this issue in Schemr by catching the `ValueError` when converting the invalid hex value. Please upgrade when it hits Package Control in an hour or so.

For @equinusocio can I request the [.src/schemes/scheme.tmTheme](https://github.com/equinusocio/material-theme/blob/master/.src/schemes/scheme.tmTheme) file extension be renamed to something other than `.tmTheme` to prevent it showing up as a scheme option?

**Comment by equinusocio** [comment]
@fcaldera `.src/schemes/scheme.tmTheme` should not exist. From the next release this file is no longer available
